"""
Unit Tests: Ingestion Module

Real tests for CSV, Excel, API, and factory ingestion.
"""

import json
import sys
from pathlib import Path
from unittest.mock import patch, MagicMock

import pandas as pd
import pytest

# Ensure project root is on path
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.ingestion.csv_ingestion import CSVIngestion
from src.ingestion.excel_ingestion import ExcelIngestion
from src.ingestion.api_ingestion import APIIngestion
from src.ingestion.ingestion_factory import create_ingestion, list_supported_sources
from src.errors.exceptions import IngestionError


# =====================================================================
# Fixtures
# =====================================================================

FIXTURES_DIR = PROJECT_ROOT / "tests" / "fixtures"


@pytest.fixture
def valid_csv_path():
    """Path to a valid CSV fixture (generated by generate_sample_data.py)."""
    path = FIXTURES_DIR / "sample_transactions.csv"
    if not path.exists():
        # Create a minimal fixture for testing
        df = pd.DataFrame({
            "transaction_id": ["TXN-001", "TXN-002", "TXN-003"],
            "customer_id": ["CUST-1001", "CUST-1002", "CUST-1003"],
            "product_id": ["PROD-001", "PROD-002", "PROD-003"],
            "transaction_date": ["2024-01-15", "2024-02-20", "2024-03-10"],
            "quantity": [2, 1, 5],
            "unit_price": [45000.00, 22000.00, 1500.00],
            "total_amount": [90000.00, 22000.00, 7500.00],
            "location": ["Hyderabad", "Mumbai", "Delhi"],
        })
        path.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(path, index=False)
    return path


@pytest.fixture
def valid_excel_path(valid_csv_path):
    """Path to a valid Excel fixture."""
    path = FIXTURES_DIR / "sample_transactions.xlsx"
    if not path.exists():
        df = pd.read_csv(valid_csv_path)
        df.to_excel(path, index=False, engine="openpyxl")
    return path


@pytest.fixture
def nonexistent_path(tmp_path):
    """Path to a file that does not exist."""
    return tmp_path / "does_not_exist.csv"


# =====================================================================
# CSV Ingestion Tests
# =====================================================================

class TestCSVIngestion:
    """Tests for CSVIngestion."""

    def test_extract_valid_csv(self, valid_csv_path):
        """CSV with valid data returns a non-empty DataFrame."""
        adapter = CSVIngestion(file_path=valid_csv_path)
        df = adapter.extract()

        assert isinstance(df, pd.DataFrame)
        assert len(df) > 0
        assert "transaction_id" in df.columns

    def test_source_type(self, valid_csv_path):
        """source_type property returns 'csv'."""
        adapter = CSVIngestion(file_path=valid_csv_path)
        assert adapter.source_type == "csv"

    def test_source_name(self, valid_csv_path):
        """source_name returns the file path."""
        adapter = CSVIngestion(file_path=valid_csv_path)
        assert str(valid_csv_path) in adapter.source_name

    def test_file_not_found_raises_ingestion_error(self, nonexistent_path):
        """Missing file raises IngestionError."""
        adapter = CSVIngestion(file_path=nonexistent_path)
        with pytest.raises(IngestionError, match="not found"):
            adapter.extract()

    def test_extract_returns_correct_columns(self, valid_csv_path):
        """Extracted DataFrame has expected columns."""
        adapter = CSVIngestion(file_path=valid_csv_path)
        df = adapter.extract()
        expected_cols = {"transaction_id", "customer_id", "product_id",
                         "transaction_date", "quantity", "unit_price",
                         "total_amount", "location"}
        assert expected_cols.issubset(set(df.columns))


# =====================================================================
# Excel Ingestion Tests
# =====================================================================

class TestExcelIngestion:
    """Tests for ExcelIngestion."""

    def test_extract_valid_excel(self, valid_excel_path):
        """Excel file with valid data returns a non-empty DataFrame."""
        adapter = ExcelIngestion(file_path=valid_excel_path)
        df = adapter.extract()

        assert isinstance(df, pd.DataFrame)
        assert len(df) > 0
        assert "transaction_id" in df.columns

    def test_source_type(self, valid_excel_path):
        """source_type property returns 'excel'."""
        adapter = ExcelIngestion(file_path=valid_excel_path)
        assert adapter.source_type == "excel"

    def test_file_not_found_raises_ingestion_error(self, nonexistent_path):
        """Missing file raises IngestionError."""
        nonexistent_xlsx = nonexistent_path.with_suffix(".xlsx")
        adapter = ExcelIngestion(file_path=nonexistent_xlsx)
        with pytest.raises(IngestionError, match="not found"):
            adapter.extract()


# =====================================================================
# API Ingestion Tests
# =====================================================================

class TestAPIIngestion:
    """Tests for APIIngestion."""

    def test_extract_valid_response(self):
        """Valid JSON response with records returns a DataFrame."""
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "dataset": "transactions",
            "records": [
                {"transaction_id": "TXN-001", "amount": 100.0},
                {"transaction_id": "TXN-002", "amount": 200.0},
            ],
        }

        with patch("src.ingestion.api_ingestion.requests.get", return_value=mock_response):
            adapter = APIIngestion(url="http://test.example.com/api/data")
            df = adapter.extract()

        assert isinstance(df, pd.DataFrame)
        assert len(df) == 2
        assert "transaction_id" in df.columns

    def test_source_type(self):
        """source_type property returns 'api'."""
        adapter = APIIngestion(url="http://test.example.com/api")
        assert adapter.source_type == "api"

    def test_http_error_raises_ingestion_error(self):
        """Non-200 HTTP status raises IngestionError."""
        mock_response = MagicMock()
        mock_response.status_code = 500
        mock_response.text = "Internal Server Error"

        with patch("src.ingestion.api_ingestion.requests.get", return_value=mock_response):
            adapter = APIIngestion(url="http://test.example.com/api/data")
            with pytest.raises(IngestionError, match="HTTP 500"):
                adapter.extract()

    def test_connection_error_raises_ingestion_error(self):
        """Network failure raises IngestionError."""
        import requests as req

        with patch("src.ingestion.api_ingestion.requests.get",
                   side_effect=req.exceptions.ConnectionError("refused")):
            adapter = APIIngestion(url="http://unreachable.example.com/api")
            with pytest.raises(IngestionError, match="connection failed"):
                adapter.extract()

    def test_timeout_raises_ingestion_error(self):
        """Request timeout raises IngestionError."""
        import requests as req

        with patch("src.ingestion.api_ingestion.requests.get",
                   side_effect=req.exceptions.Timeout("timed out")):
            adapter = APIIngestion(url="http://slow.example.com/api", timeout=1)
            with pytest.raises(IngestionError, match="timed out"):
                adapter.extract()

    def test_missing_records_key_raises_ingestion_error(self):
        """JSON without 'records' key raises IngestionError."""
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {"dataset": "test"}

        with patch("src.ingestion.api_ingestion.requests.get", return_value=mock_response):
            adapter = APIIngestion(url="http://test.example.com/api/data")
            with pytest.raises(IngestionError, match="missing"):
                adapter.extract()


# =====================================================================
# Ingestion Factory Tests
# =====================================================================

class TestIngestionFactory:
    """Tests for ingestion_factory."""

    def test_create_csv_adapter(self, valid_csv_path):
        """Factory returns a CSVIngestion for source_type='csv'."""
        adapter = create_ingestion("csv", file_path=valid_csv_path)
        assert isinstance(adapter, CSVIngestion)
        assert adapter.source_type == "csv"

    def test_create_excel_adapter(self, valid_excel_path):
        """Factory returns an ExcelIngestion for source_type='excel'."""
        adapter = create_ingestion("excel", file_path=valid_excel_path)
        assert isinstance(adapter, ExcelIngestion)
        assert adapter.source_type == "excel"

    def test_create_api_adapter(self):
        """Factory returns an APIIngestion for source_type='api'."""
        adapter = create_ingestion("api", url="http://test.example.com/api")
        assert isinstance(adapter, APIIngestion)
        assert adapter.source_type == "api"

    def test_unsupported_source_raises_error(self):
        """Unknown source type raises IngestionError."""
        with pytest.raises(IngestionError, match="Unsupported"):
            create_ingestion("ftp", path="/data")

    def test_list_supported_sources(self):
        """list_supported_sources returns known types."""
        sources = list_supported_sources()
        assert "csv" in sources
        assert "excel" in sources
        assert "api" in sources
        assert "database" in sources

    def test_case_insensitive(self, valid_csv_path):
        """Factory handles upper/mixed case source types."""
        adapter = create_ingestion("CSV", file_path=valid_csv_path)
        assert isinstance(adapter, CSVIngestion)
